---
title: "A liltte about me"
---

I am Brazilian but I live in Sweden for almost 5 years now with my wife Ana and our little son, Bento. I have a PhD in Peace, Defense and International Security from the San Tiago Dantas Graduate Programe of the São Paulo State University in São Paulo, Brazil.

Being South American has really shaped my research interests. The history of military coups and dictatorships has pushed my research to understand how the institutions, political power and resource allocation to the military interact. I look at military expenditures from those lenses: not just an input for military might, but as the outcome of a particular constellation of interests. 

While my basic scientific training was mostly qualitative, I've grown to appreciate quantitative methods more and more over the years. Besides being an interesting topic in and of itself, statistics is an extremely powerful tool - specially when combined with sound qualitative work. I have also grown to love programming in R. If you ask me, R is everything science needs to be: open access, collaborative and reproducible. Anyone anywhere can use it and produce insights, which is amazing to me. While I do like to preach the word of R, I am also familiar with Stata.

Lastly, if there is one thing you should know about me is that I am curious. The reason I chose to study International Relations is because it covers so much ground. I got to study many of the things I was passionate about, like History, Economics, Sociology and so on. But I am also interested in many things besides International Relations. The thing I read the most about is certainly Philosophy, but lately I've been reading a lot of history of mathematics - being mathematical problems or biographies of mathematicians. You can check my Goodreads page to see what I have been reading.
