---
title: "My favourite anecdote on Wittgenstein"
author: "Diego Lopes da Silva"
date: "2025-02-05"
categories: [Ramblings]
description: "On Wittgenstein's intense gaze, Russell's dull biography, and a story about his difficult temperament that lives rent free in my mind."
---

There aren't many pictures of Wittgenstein around. In the few that remain a Google search away, his intense gaze meets you immediately. It is as if he was looking at you before you met his eyes, before clicked on the link to open the picture. Spooky stuff.

I've read a few things about the guy. Very interesting fella. I went through the painful business of reading Bertrand Russell's biography just to get a glimpse of his relationship with Wittgenstein. Let me clarify that I say painful not because it was poorly written or researched. The biographer in question is Ray Monk, who has also written Wittgenstein's biography. The reason it was a painful experience is that I found Russell to be a terribly dull fella. But we can talk about that some other time. Back to my pal Witt.

Wittgenstein was hard to deal with and one of the many instances of his difficult temperament lives rent free in my mind. His sister
